# SPDX-License-Identifier: GPL-2.0-or-later

KEY_SIZE_RATIO = 3.3
KEY_SPACING_RATIO = 0.15
KEY_ROUNDNESS = 0.1

KEYCODE_BTN_RATIO = 3

# Base window size - will be scaled based on device pixel ratio
WINDOW_WIDTH, WINDOW_HEIGHT = 1024, 768

KEYBOARD_WIDGET_PADDING = 4

KEYBOARD_WIDGET_MASK_HEIGHT = 0.65
KEYBOARD_WIDGET_NONMASK_PADDING = 0.02

SHADOW_SIDE_PADDING = 0.05
SHADOW_TOP_PADDING = 0.05
SHADOW_BOTTOM_PADDING = 0.07

# HiDPI Support
# These will be set based on screen DPI at runtime
HIDPI_SCALE = 1.1
MIN_WINDOW_WIDTH = 800
MIN_WINDOW_HEIGHT = 600
PREFERRED_WINDOW_WIDTH = 1200
PREFERRED_WINDOW_HEIGHT = 900
